on:
  workflow_dispatch:

jobs:
  iac_test:
    steps:
        - uses: leonardotatsch/pipeline-templates/.github/workflows/terraform-plan.yml@main
          with: 
            terraform_version: '1.3.3'
            infracost_enabled: false
            working-directory: ${{ env.working-directory }}