name: IaC test

on:
  workflow_dispatch:

jobs:
  build:
    uses: leonardotatsch/pipeline-templates/.github/workflows/terraform-plan.yml@main
    with:
      working-directory: "./tf"
      terraform-version: "1.3.3"
      storage_account_name: "saiacltatschc"
      container_name: "terraform"
      tf_file_name: "azaccelerator.tfstate"
      resource_group_name: "rg-ltatschc"
      environment: "sandbox"
    secrets:
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
    #secrets: inherit